USE QLHANG
---TAO BANG VAT TU
CREATE TABLE VATTU (
	MAVT CHAR(5) PRIMARY KEY,
	TENVT NVARCHAR(25),
	DVTINH NVARCHAR(10),
	SLCON INT
)
---TAO BANG HOA DON BAN
CREATE TABLE HDBAN (
	MAHD VARCHAR(10) PRIMARY KEY,
	NGAYXUAT SMALLDATETIME,
	HOTENKHACH NVARCHAR(25)
)
-- TAO BANG HANG XUAT
CREATE TABLE HANGXUAT(
	MAHD VARCHAR(10),
	MAVT CHAR(5),
	DONGIA MONEY,
	SLBAN INT,
	CONSTRAINT PK_hdvt PRIMARY KEY(MAHD, MAVT)
)
--THEM DU LIEU VAO BANG VAT TU
BEGIN 
	ALTER TABLE VATTU
	NOCHECK CONSTRAINT ALL
INSERT INTO VATTU(MAVT,TENVT,DVTINH,SLCON) VALUES (N'VT01', N'XI MANG', 'VND', 50)
INSERT INTO VATTU(MAVT,TENVT,DVTINH,SLCON) VALUES(N'VT02', N'CAT', 'VND', 50)
ALTER TABLE VATTU
	CHECK CONSTRAINT ALL
END
--- THEM DU LIEU VAO BANG HOA DON BAN
BEGIN 
	ALTER TABLE HDBAN
	NOCHECK CONSTRAINT ALL
INSERT INTO HDBAN(MAHD,NGAYXUAT,HOTENKHACH) VALUES(N'HD01',CAST(N'2022-12-12'AS DATE),N'Nguyen Anh Toi')
INSERT INTO HDBAN(MAHD,NGAYXUAT,HOTENKHACH) VALUES(N'HD02',CAST(N'2020-10-10'AS DATE),N'Nguyen Minh Khoi')
ALTER TABLE HDBAN
	CHECK CONSTRAINT ALL
END
--- THEM DU LIEU VAO BANG HANG XUAT
BEGIN 
	ALTER TABLE HANGXUAT
	NOCHECK CONSTRAINT ALL
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD02',N'VT11',150000, 200)
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD03',N'VT12',200000, 400)
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD04',N'VT13',120000, 300)
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD05',N'VT14',70000, 100)
ALTER TABLE HANGXUAT
	CHECK CONSTRAINT ALL
END
----CAU 2
SELECT TOP 1 MAHD, SUM(DONGIA) AS TONG_TIEN 
FROM HANGXUAT 
GROUP BY MAHD,DONGIA 
ORDER BY DONGIA DESC

--CAU3
CREATE FUNCTION CAU5  (@MAHD VARCHAR(10))
RETURNS TABLE
AS
RETURN
    SELECT HX.MAHD,HD.NGAYXUAT,HX.MAVT, HX.DONGIA,HX.SLBAN,
        CASE
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Monday'THEN N'Thứ Hai'            
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Tuesday'THEN N'Thứ Ba'
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Wednesday'THEN N'Thứ Tư'
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Thursday'THEN N'Thứ Năm'
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Friday'THEN N'Thứ Sáu'
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Saturday'THEN N'Thứ Bảy'
			WHEN DATENAME(dw,HD.NGAYXUAT) = 'Sunday'THEN N'Chủ Nhật'
        END AS 'Ngày '
FROM HANGXUAT HX INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
WHERE HX.MAHD = @MAHD;


---CAU4
CREATE PROCEDURE CAU4  @THANG INT, @NAM INT 
AS
SELECT 
	SUM(SLBAN * DONGIA)
	FROM HANGXUAT HX INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
    WHERE MONTH(HD.NGAYXUAT) = @THANG AND YEAR(HD.NGAYXUAT) = @NAM;
SELECT TOP 1 MAHD, SUM(DONGIA) AS TongTien 
FROM HANGXUAT 
GROUP BY MAHD,DONGIA
ORDER BY DONGIA DESC


